/* global React */
// Project data — 8 projects, each with metadata + gallery placeholders
const PROJECTS = [
  {
    id: "ello",
    no: "01",
    title: "Ello",
    subtitle: "Home Café Branding",
    year: "2025",
    role: "Brand Identity / Packaging",
    color: "#FFF6E6",
    accent: "#4682B4",
    desc: "Ello brings the café home — high-quality coffee beans, premium Japanese matcha powder, and fresh pet-friendly meals, all delivered to your door so you and your furry friend can slow down together. The identity is built around two curious mascots, Bluppi and friend, a tight tri-colour palette (Basil, Sunlit, Bluppi blue), and a chunky geometric wordmark that reads as warmly as a hello.",
    challenge: "Most home-café brands lean cold and minimal — premium-as-coldness. Ello had to feel premium and warm at once, and unusual: a café brand that genuinely belongs to the pets in the room as much as the humans. The challenge was building a system playful enough to put a dog face on a coffee bag without losing the discipline of a real food brand — a colour palette, a packaging grid, and a mascot that could carry coffee, matcha, ice cream, and pet meals without breaking.",
    deliverables: ["Logo & wordmark", "Mascot system", "Coffee + matcha packaging", "Pet-food line", "Brand strategy", "Brand video"],
    video: "https://www.youtube.com/watch?v=0WPvZkf2-LY",
    images: {
      hero: "assets/projects/ello/strategy.png",
      gallery: [
        { src: "assets/projects/ello/strategy.png", span: 12, label: "Brand system" },
        { src: "assets/projects/ello/summer.png", span: 6, label: "Ello Summer — light roast" },
        { src: "assets/projects/ello/roast.png", span: 6, label: "Ello Roast — medium roast" },
        { src: "assets/projects/ello/matcha.png", span: 7, label: "Matcha & touchpoints" },
        { src: "assets/projects/ello/icecream.png", span: 5, label: "Pet-friendly ice cream" },
        { src: "assets/projects/ello/lineup.png", span: 6, label: "Shipping box" },
        { src: "assets/projects/ello/box.png", span: 6, label: "Full product line-up" },
        { src: "assets/projects/ello/brand-system.png", span: 12, label: "Brand strategy: when / where / why / how" },
      ]
    },
    span: "span-7",
    aspect: "wide",
  },
  {
    id: "wuwei",
    no: "02",
    title: "無為",
    subtitle: "This book won't help you",
    year: "2025",
    role: "Editorial / Thesis",
    color: "#1F1F1F",
    accent: "#B6FF3D",
    desc: "Graphic Design Thesis — an experimental book that resists self-help conventions. Recipient of three 2025 RGD Student Awards Honourable Mentions: Award for Storytelling, Award for Editorial Design, and Best in Show consideration.",
    challenge: "Translate the Daoist concept of wú wéi (effortless action) into a book object that lets the reader stop trying.",
    deliverables: ["256pp book design", "Cover system", "Custom typography", "Bilingual layout (中/EN)"],
    awards: ["RGD 2025 — Storytelling (HM)", "RGD 2025 — Editorial Design (HM)"],
    images: {
      hero: "assets/projects/wuwei/main.png",
      gallery: [
        { src: "assets/projects/wuwei/main.png", span: 0, label: "Book cover" },
        { src: "assets/projects/wuwei/bookmark set.png", span: 6, label: "bookmark set" },
        { src: "assets/projects/wuwei/process book.png", span: 6, label: "process book" },
        { src: "assets/projects/wuwei/matcha.png", span: 7, label: "Matcha & touchpoints" },
        { src: "assets/projects/wuwei/icecream.png", span: 5, label: "Pet-friendly ice cream" },
        { src: "assets/projects/wuwei/lineup.png", span: 6, label: "Shipping box" },
        { src: "assets/projects/wuwei/box.png", span: 6, label: "Full product line-up" },
        { src: "assets/projects/wuwei/brand-system.png", span: 12, label: "Brand strategy: when / where / why / how" },
      ]
    },
    span: "span-5",
    aspect: "tall",
  },
  {
    id: "tai-ping",
    no: "03",
    title: "Cheung Chau Tai Ping Ching Chau",
    subtitle: "Festival Poster Series & Timeline",
    year: "2024",
    role: "Poster / Information Design",
    color: "#E8443A",
    accent: "#F2C94C",
    desc: "A poster series and timeline graphic celebrating Hong Kong's iconic Bun Festival. Pulls from temple banners, talisman type, and the chaotic joy of the bun-snatching tower.",
    challenge: "Honour a tradition without flattening it into a tourist poster — keep the strangeness, the smoke, the speed.",
    deliverables: ["3-poster series", "Foldable timeline", "Type explorations"],
    span: "span-5",
    aspect: "poster",
  },
  {
    id: "blissful",
    no: "04",
    title: "Blissful",
    subtitle: "Magazine",
    year: "2024",
    role: "Editorial",
    color: "#FFD7DD",
    accent: "#FF6F91",
    desc: "Blissful is a crochet magazine that turns a slow, tactile craft into a vibrant invitation. Built for Gen Z and millennial beginners, it pairs bold colour, playful typography, and a lively grid system to make a centuries-old hobby feel fresh — a gentle off-screen escape that nurtures mindfulness, focus, and the small joy of finishing something with your own hands.",
    challenge: "Crochet has a marketing problem: the work is beautiful, but the visual world around it can feel dated and intimidating to anyone under 40. Blissful had to rebuild that first impression. The challenge was designing a magazine loud enough to stop a Gen Z scroll, soft enough to feel like a wind-down ritual, and clear enough that a true beginner could follow a pattern from page one.",
    deliverables: ["64pp magazine", "Cover series", "Editorial system", "Pattern guides"],
    span: "span-7",
    aspect: "wide",
  },
  {
    id: "cloverleaf",
    no: "05",
    title: "Clover Leaf",
    subtitle: "Packaging Redesign",
    year: "2024",
    role: "Packaging / Brand",
    color: "#0E5C3A",
    accent: "#F4E29A",
    desc: "A packaging redesign for the canned seafood staple — keeping the heritage cue of the clover, but giving the line a sharper, more contemporary shelf presence.",
    challenge: "Modernise without losing the trust shoppers feel for the original can.",
    deliverables: ["Can label system", "Variant family", "Mock retail comps"],
    span: "span-4",
    aspect: "square",
  },
  {
    id: "goodday",
    no: "06",
    title: "Good Day!",
    subtitle: "Mobile App",
    year: "2024",
    role: "Product / UI",
    color: "#FFE873",
    accent: "#3B5BDB",
    desc: "A mood-tracking app designed around small daily wins rather than productivity. Soft, cheerful UI that lets you log a 'good thing' in under five seconds.",
    challenge: "Make a wellness app that doesn't feel like homework.",
    deliverables: ["Product UI", "Brand system", "Onboarding flow"],
    span: "span-4",
    aspect: "tall",
  },
  {
    id: "fernno",
    no: "07",
    title: "Fernno",
    subtitle: "Branding",
    year: "2023",
    role: "Brand Identity",
    color: "#2D3A2A",
    accent: "#A4C76E",
    desc: "Identity work for an indoor-plant studio: a wordmark with quiet personality, a botanical mark, and a tag system that grows with the brand.",
    challenge: "Build a plant brand that doesn't lean on the most-obvious leaf clichés.",
    deliverables: ["Wordmark", "Pattern system", "Tags & labels"],
    span: "span-5",
    aspect: "long",
  },
  {
    id: "fujii",
    no: "08",
    title: "Fujii Kaze",
    subtitle: "Toronto Concert Stickers",
    year: "2025",
    role: "Illustration / Merch",
    color: "#C7FF3D",
    accent: "#0A0A0A",
    desc: "A fan-made sticker series for Fujii Kaze's Danforth Music Hall stop on his 2025 North America Tour. Hand-drawn lettering in English and 藤井風 (Japanese kanji), wrapped with concert details, the CN Tower, a maple leaf, and a tiny flower — printed in two colourways and a holographic finish, given away for free at the show to spread the love.",
    challenge: "Translate the energy of a live Fujii Kaze set — playful, generous, a little chaotic — into a 3-inch object that fans could carry home. The lettering had to feel hand-made (not a logo lift), bilingual without one language dominating, and bold enough to work on neon yellow, glossy holo, and risograph green.",
    deliverables: ["Hand-drawn lettering (EN + 日本語)", "Poster variants", "Holographic & matte stickers", "Free giveaway run"],
    images: {
      hero: "assets/projects/fujii/poster-01.png",
      gallery: [
        { src: "assets/projects/fujii/poster-01.png", span: 12, label: "Yellow tour poster — Danforth Music Hall, Toronto" },
        { src: "assets/projects/fujii/poster-03.png", span: 6, label: "Green grain poster — risograph treatment" },
        { src: "assets/projects/fujii/poster-06.png", span: 6, label: "Layout system & giveaway note (EN + 日本語)" },
        { src: "assets/projects/fujii/holographic-pile.jpg", span: 6, label: "Holographic & matte sticker pile" },
        { src: "assets/projects/fujii/riso-neon.jpg", span: 6, label: "Risograph neon green stack" },
        { src: "assets/projects/fujii/sticker-sheet.jpg", span: 12, label: "Uncut sticker sheet — six colourways before trimming", rotate: 90 },
      ]
    },
    span: "span-5",
    aspect: "tall",
  },
];

window.PROJECTS = PROJECTS;
