/* global React */
// Project data — 8 projects, each with metadata + gallery placeholders
const PROJECTS = [
  {
    id: "ello",
    no: "No.01",
    title: "Ello",
    subtitle: "Home Café Branding",
    year: "2025",
    role: "Brand Identity / Packaging",
    color: "#FFF6E6",
    accent: "#4682B4",
    desc: "Ello brings the café home — high-quality coffee beans, premium Japanese matcha powder, and fresh pet-friendly meals, all delivered to your door so you and your furry friend can slow down together. The identity is built around two curious mascots, Bluppi and friend, a tight tri-colour palette (Basil, Sunlit, Bluppi blue), and a chunky geometric wordmark that reads as warmly as a hello.",
    challenge: "Most home-café brands lean cold and minimal — premium-as-coldness. Ello had to feel premium and warm at once, and unusual: a café brand that genuinely belongs to the pets in the room as much as the humans. The challenge was building a system playful enough to put a dog face on a coffee bag without losing the discipline of a real food brand — a colour palette, a packaging grid, and a mascot that could carry coffee, matcha, ice cream, and pet meals without breaking.",
    deliverables: ["Logo & wordmark", "Mascot system", "Coffee + matcha packaging", "Pet-food line", "Brand strategy", "Brand video"],
    video: "https://www.youtube.com/watch?v=0WPvZkf2-LY",
    images: {
      hero: "assets/projects/ello/strategy.png",
      gallery: [
        { src: "assets/projects/ello/strategy.png", span: 12, label: "Brand system" },
        { src: "assets/projects/ello/summer.png", span: 6, label: "Ello Summer — light roast" },
        { src: "assets/projects/ello/roast.png", span: 6, label: "Ello Roast — medium roast" },
        { src: "assets/projects/ello/matcha.png", span: 7, label: "Matcha & touchpoints" },
        { src: "assets/projects/ello/icecream.png", span: 5, label: "Pet-friendly ice cream" },
        { src: "assets/projects/ello/lineup.png", span: 6, label: "Shipping box" },
        { src: "assets/projects/ello/box.png", span: 6, label: "Full product line-up" },
        { src: "assets/projects/ello/brand-system.png", span: 12, label: "Brand strategy: when / where / why / how" },
      ]
    },
    
    span: "span-7",
    aspect: "wide",
  },
  {
    id: "wuwei",
    no: "No.02",
    title: "無為: This book won't help you",
    subtitle: "2025 RGD Student Awards Honourable Mention in: Award for Storytelling & Award for Editorial Design",
    year: "2025",
    role: "Editorial / Thesis",
    color: "none",
    accent: "#B6FF3D",
    desc: "Graphic Design Thesis — an experimental book that resists self-help conventions. Recipient of two 2025 RGD Student Awards Honourable Mentions: Award for Storytelling, Award for Editorial Design.",
    challenge: "Explore alternative sources of happiness, wisdom, and solace to build a meaningful life that doesn’t require years of expensive psychotherapy. This bilingual book won’t give you answers. But it might feel like a walk to the temple in your mind from Chapter 1: Me to beyond. You don’t always know what you’re looking for, yet somehow leave feeling a little lighter. It’s a gentle invitation to reflect, feel, and carry on — You’re already enough.",
    deliverables: ["256pp book design", "Cover system", "Custom typography", "Bilingual layout (中/EN)"],
    awards: ["RGD 2025 — Storytelling (HM)", "RGD 2025 — Editorial Design (HM)"],
    images: {
      hero: "assets/projects/wuwei/main.png",
      gallery: [
        { src: "assets/projects/wuwei/bookmark set.png", span: 4, label: "bookmark set" },
        { src: "assets/projects/wuwei/main.png", span: 4, label: "Book cover" },
        { src: "assets/projects/wuwei/process book.png", span: 4, label: "process book" },
        { src: "assets/projects/wuwei/bookmark.gif", span: 6, label: "bookmark design" },
        { src: "assets/projects/wuwei/Comp 1.gif", span: 6, label: "bookmark design" },
        { src: "assets/projects/wuwei/thesis_book.png", span: 6, label: "Thesis book" },
        { src: "assets/projects/wuwei/thesis_bookmarks.png", span: 6, label: "Full product line-up" },
        { src: "assets/projects/wuwei/book the book2-08.png", span: 6, },
        { src: "assets/projects/wuwei/book the book2-23.png", span: 6, },
        { src: "assets/projects/wuwei/book the book2-24.png", span: 6, },
        { src: "assets/projects/wuwei/book the book2-27.png", span: 6, },
        { src: "assets/projects/wuwei/2025StudentAwards_stickers_HM-white.png", span: 4, },
      ]
    },
    video: "https://www.youtube.com/watch?v=4twa7ZjuiiA",
    span: "span-5",
    aspect: "tall",
  },
  {
    id: "tai-ping",
    no: "03",
    title: "Cheung Chau Tai Ping Ching Chau",
    subtitle: "Festival Poster Series & Timeline",
    year: "2024",
    role: "Poster / Information Design",
    color: "none",
    accent: "#F2C94C",
    desc: "A poster series and timeline graphic celebrating Hong Kong's iconic Bun Festival. Pulls from temple banners, talisman type, and the chaotic joy of the bun-snatching tower.",
    challenge: "The design aims to engage younger generations and a wider audience interested in Hong Kong’s cultural celebrations. By blending traditional festival elements with innovative typefaces, vibrant colours, and hand-drawn illustrations of cultural traditions.",
    deliverables: ["3-poster series", "Foldable timeline", "Type explorations"],
    span: "span-4",
    aspect: "poster",
    images: {
      hero: "assets/projects/TaiPing/Bethany_Fung_3posters-06.png",
      gallery: [
        { src: "assets/projects/TaiPing/Bethany_Fung_3posters-07.png", span: 4, },
        { src: "assets/projects/TaiPing/Bethany_Fung_3posters-06.png", span: 4, },
        { src: "assets/projects/TaiPing/Bethany_Fung_3posters-04.png", span: 4, },
        { src: "assets/projects/TaiPing/GBCTYPE3-TypeAsInfo-Process.png", span: 12, label: "Timeline" },
        { src: "assets/projects/TaiPing/timebunfes.png.webp", span: 6 },
        { src: "assets/projects/TaiPing/Image 2023-10-10 at 12.50 AM.jpg", span: 6},
        { src: "assets/projects/TaiPing/gold.png", span: 4, },
        { src: "assets/projects/TaiPing/buns tower.png", span: 4, },
        { src: "assets/projects/TaiPing/poster mockup.png", span: 12, },
        { src: "assets/projects/TaiPing/Sprint 2.png", span: 12, },
      ]
    },
  },
  {
    id: "blissful",
    no: "No.04",
    title: "Blissful",
    subtitle: "Magazine",
    year: "2024",
    role: "Editorial",
    color: "none",
    accent: "#FF6F91",
    desc: "Blissful is a crochet magazine that turns a slow, tactile craft into a vibrant invitation. Built for Gen Z and millennial beginners, it pairs bold colour, playful typography, and a lively grid system to make a centuries-old hobby feel fresh — a gentle off-screen escape that nurtures mindfulness, focus, and the small joy of finishing something with your own hands.",
    challenge: "Crochet has a marketing problem: the work is beautiful, but the visual world around it can feel dated and intimidating to anyone under 40. Blissful had to rebuild that first impression. The challenge was designing a magazine loud enough to stop a Gen Z scroll, soft enough to feel like a wind-down ritual, and clear enough that a true beginner could follow a pattern from page one.",
    deliverables: ["64pp magazine", "Cover series", "Editorial system", "Pattern guides"],
    span: "span-4",
    aspect: "poster",
     images: {
      hero: "assets/projects/blissful/P05.png",
      gallery: [
        { src: "assets/projects/blissful/Page 10.png", span: 12, },
        { src: "assets/projects/blissful/Page 6.png", span: 12, },
        { src: "assets/projects/blissful/Page 7.png", span: 12, },
        { src: "assets/projects/blissful/Page 3.png", span: 12, },
        { src: "assets/projects/blissful/Page 9.png", span: 12 },
        { src: "assets/projects/blissful/Page 2.png", span: 12, },
        { src: "assets/projects/blissful/Page 8.png", span: 12},
        { src: "assets/projects/blissful/Page 5.png", span: 12, },
        { src: "assets/projects/blissful/Page 1.png", span: 12, },
        { src: "assets/projects/blissful/Page 4.png", span: 12, },
      ]
    },
  },
  {
    id: "cloverleaf",
    no: "05",
    title: "Clover Leaf",
    subtitle: "Packaging Redesign",
    year: "2024",
    role: "Packaging / Brand",
    color: "none",
    accent: "#F4E29A",
    desc: "A packaging redesign for the canned tuna staple — keeping the heritage cue of the clover, but giving the line a sharper, more contemporary shelf presence.",
    challenge: "Modernise without losing the trust shoppers feel for the original can.",
    deliverables: ["Can label system", "Variant family", "Mock retail comps"],
    span: "span-4",
    aspect: "square",
    images: {
      hero: "assets/projects/cloverleaf/Small-Food-Can-1.png",
      gallery: [
        { src: "assets/projects/cloverleaf/Small-Food-Can-11.png", span: 6, label: "Dill & Lemon" },
        { src: "assets/projects/cloverleaf/Small-Food-Can-10.png", span: 6, label: "Dill & Lemon" },
        { src: "assets/projects/cloverleaf/Small-Food-Can-5.png", span: 6, label: "Spicy Thai Chili" },
        { src: "assets/projects/cloverleaf/Small-Food-Can-6.png", span: 6, label: "Spicy Thai Chili" },
        { src: "assets/projects/cloverleaf/Small-Food-Can-3.png", span: 4, label: "Lemon & Pepper" },
        { src: "assets/projects/cloverleaf/Small-Food-Can-1.png", span: 4, label: "Lemon & Pepper" },
        { src: "assets/projects/cloverleaf/Small-Food-Can-8.png", span: 4, label: "Lemon & Pepper" },
      ]
    },
  },
  {
    id: "dribbble",
    no: "No.06",
    title: "dribbble client - RC advance & Hobbies",
    subtitle: "Logo",
    year: "2025",
    role: "Branding",
    color: "#ffffff",
    accent: "#3B5BDB",
    desc: "A logo design for a family-run R/C hobby shop based in Markham, focused on remote-controlled cars and automotive culture. The goal was to create a simple, flexible identity that reflects the energy of the hobby while staying approachable for a local community.",
    challenge: "I developed two distinct moodboards based on the client’s references, each framing a slightly different tone. From there, I created multiple logo variations, testing different forms, compositions, and visual weights. This allowed the client to compare directions side-by-side and make a more confident decision about what best represents their shop. Instead of a single option, the client received a small system of logo variations and a clearer sense of their brand identity. This extra step to small business. a wellness app that doesn't feel like homework.",
    deliverables: ["Logo designs", "Brand identity"],
    span: "span-4",
    aspect: "square",
    images: {
      hero: "assets/projects/dribbble/Artboard2.png",
      gallery: [
        { src: "assets/projects/dribbble/Artboard1.png", span: 12, label: "Logo variation" },
        { src: "assets/projects/dribbble/reference image 1.png", span: 6, label: "Mock up" },
        { src: "assets/projects/dribbble/og.png", span: 6, label: "Original logo design" },
        { src: "assets/projects/dribbble/Red stickers mockup.png", span: 6, label: "Stickers" },
        { src: "assets/projects/dribbble/Artboard2.png", span: 6, label: "main logo design" },

      ]
    },
  },
  {
    id: "fernno",
    no: "07",
    title: "Fernno",
    subtitle: "Branding",
    year: "2023",
    role: "Brand Identity",
    color: "none",
    accent: "#A4C76E",
    desc: "Identity work for an indoor-plant studio: a wordmark with quiet personality, a botanical mark, and a tag system that grows with the brand.",
    challenge: "Build a plant brand that doesn't lean on the most-obvious leaf clichés.",
    deliverables: ["Wordmark", "Pattern system", "Tags & labels"],
    span: "span-6",
    aspect: "wide",
     images: {
      hero: "assets/projects/fernno/logo1.png",
      gallery: [
        { src: "assets/projects/fernno/brandmark-08.png", span: 3, },
        { src: "assets/projects/fernno/brandmark-09.png", span: 3, },
        { src: "assets/projects/fernno/brandmark-10.png", span: 3, },
        { src: "assets/projects/fernno/brandmark-11.png", span: 3, },
                { src: "assets/projects/fernno/logo1.png", span: 8, },
        { src: "assets/projects/fernno/yellow.png", span: 1.5, },
        { src: "assets/projects/fernno/red.png", span: 1.5, },
        { src: "assets/projects/fernno/blue.png", span: 1.5, },
        { src: "assets/projects/fernno/green.png", span: 1.5, },
        { src: "assets/projects/fernno/Mailer_Box_white.png", span: 6, },
        { src: "assets/projects/fernno/Mailer_Box_Mockup_3.png", span: 6, },
        { src: "assets/projects/fernno/helmet.png", span: 6, },
        { src: "assets/projects/fernno/helmet2.png", span: 6, },
        { src: "assets/projects/fernno/CAP.png", span: 6, },
        { src: "assets/projects/fernno/WaterBottleMockup.png", span: 6, },
        { src: "assets/projects/fernno/Shopping Tote Bag.png", span: 4, },
        { src: "assets/projects/fernno/Elevator Door.png", span: 8, },
        { src: "assets/projects/fernno/insta2.png", span: 4, },
        { src: "assets/projects/fernno/insta1.png", span: 4, },
        { src: "assets/projects/fernno/web-mockup2.png", span: 4,},
        { src: "assets/projects/fernno/web-mockup1.png", span: 4,},
        { src: "assets/projects/fernno/Free-Employee-ID-Card-Holder-Mockup.png", span: 4, },
        { src: "assets/projects/fernno/tee1.png", span: 4, },
        { src: "assets/projects/fernno/Shop Window Mockup.png", span: 12, },


      ]
    },
  },
  {
    id: "fujii",
    no: "08",
    title: "Fujii Kaze",
    subtitle: "Toronto Concert Stickers",
    year: "2025",
    role: "Illustration / Merch",
    color: "none",
    accent: "#0A0A0A",
    desc: "A fan-made sticker series for Fujii Kaze's Danforth Music Hall stop on his 2025 North America Tour. Hand-drawn lettering in English and 藤井風 (Japanese kanji), wrapped with concert details, the CN Tower, a maple leaf, and a tiny flower — printed in two colourways and a holographic finish, given away for free at the show to spread the love.",
    challenge: "Translate the energy of a live Fujii Kaze set — playful, generous, a little chaotic — into a 3-inch object that fans could carry home. The lettering had to feel hand-made (not a logo lift), bilingual without one language dominating, and bold enough to work on neon yellow, glossy holo, and risograph green.",
    deliverables: ["Hand-drawn lettering (EN + Japanese)", "Poster variants", "Holographic & matte stickers", "Free giveaway run"],
    images: {
      hero: "assets/projects/fujii/poster-01.png",
      gallery: [
        { src: "assets/projects/fujii/poster-01.png", span: 12, label: "Yellow tour poster — Danforth Music Hall, Toronto" },
        { src: "assets/projects/fujii/poster-03.png", span: 6, label: "Green grain poster — risograph treatment" },
        { src: "assets/projects/fujii/poster-06.png", span: 6, label: "Layout system & giveaway note (EN + 日本語)" },
        { src: "assets/projects/fujii/holographic-pile.jpg", span: 6, label: "Holographic & matte sticker pile" },
        { src: "assets/projects/fujii/riso-neon.jpg", span: 6, label: "Risograph neon green stack" },
        { src: "assets/projects/fujii/sticker-sheet.jpg", span: 12, label: "Uncut sticker sheet — six colourways before trimming", rotate: 90 },
      ]
    },
    span: "span-4",
    aspect: "poster",

    
  },
];

window.PROJECTS = PROJECTS;
